# Generated by the argo-tui release workflow. Do not edit by hand:
# the next release overwrites this file.
class ArgoTui < Formula
  desc "Keyboard-first terminal UI for Argo Workflows"
  homepage "https://github.com/ficaa1/argo-tui"
  version "0.3.1"
  license "GPL-3.0-only"
  on_macos do
    on_arm do
      url "https://github.com/ficaa1/argo-tui/releases/download/v0.3.1/argo-tui_0.3.1_darwin_arm64.tar.gz"
      sha256 "cba6fb1cbaf691f242bb5e5f6647a56f2975a99ae9d4d8fee7e6004c9a306258"
    end
    on_intel do
      url "https://github.com/ficaa1/argo-tui/releases/download/v0.3.1/argo-tui_0.3.1_darwin_amd64.tar.gz"
      sha256 "1543e7338ba907bd454c899d15d833fcd8714b63ad0d48fbe4e93df9046b61bd"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/ficaa1/argo-tui/releases/download/v0.3.1/argo-tui_0.3.1_linux_arm64.tar.gz"
      sha256 "8d43145fd0e182384acbe65aafd215a54d06ed577fbb465707ee6d744a7c654f"
    end
    on_intel do
      url "https://github.com/ficaa1/argo-tui/releases/download/v0.3.1/argo-tui_0.3.1_linux_amd64.tar.gz"
      sha256 "88555e3015c6e30a3c077b1bf262181d33c53ad9703528cace23eac0061c71e9"
    end
  end
  def install
    bin.install "argo-tui"
  end
  test do
    assert_match version.to_s, shell_output("#{bin}/argo-tui --version")
  end
end
