# Generated by the argo-tui release workflow. Do not edit by hand:
# the next release overwrites this file.
class ArgoTui < Formula
  desc "Keyboard-first terminal UI for Argo Workflows"
  homepage "https://github.com/ficaa1/argo-tui"
  version "0.5.0"
  license "GPL-3.0-only"
  on_macos do
    on_arm do
      url "https://github.com/ficaa1/argo-tui/releases/download/v0.5.0/argo-tui_0.5.0_darwin_arm64.tar.gz"
      sha256 "0233ffee08ac30cb76547c7841f0f038f5bbf9d0843f450ac27c522bcc8c22d5"
    end
    on_intel do
      url "https://github.com/ficaa1/argo-tui/releases/download/v0.5.0/argo-tui_0.5.0_darwin_amd64.tar.gz"
      sha256 "57bb45b6a29601290c3b9e5fcb0f54b912f3e31b7680cae873bc01674a8287df"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/ficaa1/argo-tui/releases/download/v0.5.0/argo-tui_0.5.0_linux_arm64.tar.gz"
      sha256 "7c2073f0043c2e3dfcc7be4952ad4f975188276c46531758bde1a3797a6de47b"
    end
    on_intel do
      url "https://github.com/ficaa1/argo-tui/releases/download/v0.5.0/argo-tui_0.5.0_linux_amd64.tar.gz"
      sha256 "bdf2a883eb598e2b534d14bb77b022794cb3405030a5b0a2f4f266bfa0b811d2"
    end
  end
  def install
    bin.install "argo-tui"
  end
  test do
    assert_match version.to_s, shell_output("#{bin}/argo-tui --version")
  end
end
