# Generated by the micko release workflow. Do not edit by hand:
# the next release overwrites this file.
class Micko < Formula
  desc "Keyboard-first terminal UI for Argo Workflows"
  homepage "https://github.com/ficaa1/micko"
  version "0.7.1"
  license "GPL-3.0-only"
  on_macos do
    on_arm do
      url "https://github.com/ficaa1/micko/releases/download/v0.7.1/micko_0.7.1_darwin_arm64.tar.gz"
      sha256 "c4297e7d5576b7df255ac6b67be1d59786a561a13d17ac8868dafba2e92257c4"
    end
    on_intel do
      url "https://github.com/ficaa1/micko/releases/download/v0.7.1/micko_0.7.1_darwin_amd64.tar.gz"
      sha256 "b4b0564511797b9b1d2e3e4407f33fafa9e5d4bbe939c326807d175bfac44768"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/ficaa1/micko/releases/download/v0.7.1/micko_0.7.1_linux_arm64.tar.gz"
      sha256 "d364546b06c99b09a9764431762f7622cd55e43c7c49bc9b0df50ed7742e0de0"
    end
    on_intel do
      url "https://github.com/ficaa1/micko/releases/download/v0.7.1/micko_0.7.1_linux_amd64.tar.gz"
      sha256 "235979e3ec6ce269bc71c4dfa073b68a98731271dc3dc7632c570c404fb627aa"
    end
  end
  def install
    bin.install "micko"
  end
  test do
    assert_match version.to_s, shell_output("#{bin}/micko --version")
  end
end
