# Generated by the micko release workflow. Do not edit by hand:
# the next release overwrites this file.
class Micko < Formula
  desc "Keyboard-first terminal UI for Argo Workflows"
  homepage "https://github.com/ficaa1/micko"
  version "0.7.0"
  license "GPL-3.0-only"
  on_macos do
    on_arm do
      url "https://github.com/ficaa1/micko/releases/download/v0.7.0/micko_0.7.0_darwin_arm64.tar.gz"
      sha256 "2ec8eeb98a9e60768bf3ae1deabd261f0375b5d4325907c463ce8e2056c97a97"
    end
    on_intel do
      url "https://github.com/ficaa1/micko/releases/download/v0.7.0/micko_0.7.0_darwin_amd64.tar.gz"
      sha256 "3f0d3f7677ad93743d877940c8f0bcc3eace6f907754280667ff6bc31ae2bb7f"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/ficaa1/micko/releases/download/v0.7.0/micko_0.7.0_linux_arm64.tar.gz"
      sha256 "eabf0fa5e066b0be30e826d012a4d8c533412a7f9fc8db0f7c51be64bf3fc35a"
    end
    on_intel do
      url "https://github.com/ficaa1/micko/releases/download/v0.7.0/micko_0.7.0_linux_amd64.tar.gz"
      sha256 "6e3c9998e32440e6893c4f76f28ec6594e390972a47e874a58256b32da0b9e8c"
    end
  end
  def install
    bin.install "micko"
  end
  test do
    assert_match version.to_s, shell_output("#{bin}/micko --version")
  end
end
